version: '3'

services:
  verdaccio:
    restart: always
    ports:
      - '33333:4873'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - verdaccio-storage:/verdaccio/storage
      - ./conf/docker.yaml:/verdaccio/conf/config.yaml

volumes:
  verdaccio-storage:
